edgy_simple_file_root: /home/edward/edgy-ansible/roles/edgy-simple-ca/files
CA_PASS_YOU_SET: "itssecret"
CA_SUB: "/C=US/ST=New York/L=New York/O=arizone cert/OU=arizona unit/CN=teknek.io"
#This should not be the same password as the CRT as it only protects "shareable" information of the truststore
CA_TRUSTSTORE_PASSWORD: "itssemisecret"

CLIENT_FQDN: nm4
CLIENT_PASS_YOU_SET: "ssshhh"
CLIENT_SUB: "/C=US/ST=New York/L=New York/O=arizone cert/OU=arizona unit/CN={{ CLIENT_FQDN }}"




